---
- name: Deploy WordPress with LEMP Stack
  hosts: all
  become: yes
  vars:
    db_name: wordpress_db
    db_user: wp_user
    db_password: supersecret123

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install LEMP and Python Library
      apt:
        name:
          - nginx
          - mariadb-server
          - python3-pymysql
          - php-fpm
          - php-mysql
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
          - unzip
        state: present

    - name: Create Database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create Database User
      mysql_user:
        name: "{{ db_name }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*ALL"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Download and Setup WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        remote_src: yes
    
    - name: Set Permission Folder WordPress
      file:
        path: /var/www/wordpress
        owner: www-data
        group: www-data
        mode: '0755'
        recurse: yes

    - name: Copy sample config ke wp-config.php
      copy:
        src: /var/www/wordpress/wp-config-sample.php
        dest: /var/www/wordpress/wp-config.php
        remote_src: yes

    - name: Inject Database Credential ke wp-config.php
      replace:
        path: /var/www/wordpress/wp-config.php
        regexp: 'database_name_here'
        replace: "{{ db_name }}"

    - name: Set DB User di wp-config
      replace:
        path: /var/www/wordpress/wp-config.php
        regexp: 'username_here'
        replace: "{{ db_user }}"

    - name: Set DB Password di wp-config
      replace:
        path: /var/www/wordpress/wp-config.php
        regexp: 'password_here'
        replace: "{{ db_password }}"
    
    - name: Copy konfigurasi Nginx dari Laptop ke VM
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/wordpress

    - name: Enable konfigurasi WordPress (Symlink)
      file:
        src: /etc/nginx/sites-available/wordpress
        dest: /etc/nginx/sites-enabled/wordpress
        state: link

    - name: Disable konfigurasi default Nginx
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart Nginx dan PHP
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - nginx
        - php8.3-fpm
